export const events = [
  {
    id: 1,
    host_id: 1,
    host_username: 'Jeff',
    host_avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
    when: 'Sun, 15 Aug 2021 03:13:19',
    course_id: 1,
    course_name: 'Golf Waterland',
    course_url: 'https://www.amsterdamsegolfclub.nl/',
    max_players: 3,
    players: [
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
    ],
    description: 'my first event',
    title: 'my event title',
    media: 'https://blog.pinhigh.nl/wp-content/uploads/2016/07/golf-course-green.jpeg',
  },
  {
    id: 2,
    host_id: 2,
    host_username: 'Jeff',
    host_avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
    when: 'Sun, 15 Aug 2021 03:13:19',
    course_id: 2,
    course_name: 'Golf Waterland',
    course_url: 'https://www.amsterdamsegolfclub.nl/',
    max_players: 5,
    players: [
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
    ],
    description: 'my second event',
    title: 'Nice afternoon party',
    media: 'https://blog.pinhigh.nl/wp-content/uploads/2016/07/golf-course-green.jpeg',
  },
  {
    id: 3,
    host_id: 3,
    host_username: 'Jeff',
    host_avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
    when: 'Sun, 15 Aug 2021 03:13:19',
    course_id: 3,
    course_name: 'Golf Waterland',
    course_url: 'https://www.amsterdamsegolfclub.nl/',
    max_players: 3,
    players: [
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
      {
        id: 1,
        username: 'Thibault',
        avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
        handicap: 12,
      },
    ],
    description: 'my third event',
    title: 'my third title',
    media: 'https://blog.pinhigh.nl/wp-content/uploads/2016/07/golf-course-green.jpeg',
  },
];

export const user = {
  id: 1,
  username: 'Thibault',
  handicap: 12.1,
  avatar: 'https://pickaface.net/gallery/avatar/unr_random_180410_1905_z1exb.png',
};
